/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "operaciones_aritmeticas.h"


void
operador_1( char* host , int arg1, char operator, int arg2)
{
	CLIENT *clnt;
	int  *result;

	clnt = clnt_create(host, OPERADOR, ARITMETICAS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}

	if(strncmp(operator,"+",1) == 0)
		result = suma_1(arg1,arg2, clnt);
	else if(strncmp(operator,"-",1) == 0)
		result = resta_1(arg1,arg2, clnt);
	else if(strncmp(operator,"*",1) == 0)
		result = multiplicacion_1(arg1,arg2, clnt);
	else if(strncmp(operator,"/",1) == 0)
		result = division_1(arg1,arg2, clnt);
	
	if (result == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	clnt_destroy( clnt );


	/*result_1 = suma_1(suma_1_arg1, suma_1_arg2, clnt);
	if (result_1 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_2 = resta_1(resta_1_arg1, resta_1_arg2, clnt);
	if (result_2 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_3 = multiplicacion_1(multiplicacion_1_arg1, multiplicacion_1_arg2, clnt);
	if (result_3 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_4 = division_1(division_1_arg1, division_1_arg2, clnt);
	if (result_4 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	clnt_destroy( clnt );*/
}


main( int argc, char* argv[] )
{
	char *host;
	int arg1, arg2;
	char operator;

	if(argc < 5) {
		printf("usage: %s server_host entero operador entero\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	arg1 = argv[2];
	operator = argv[3];
	arg2 = argv[4];
	operador_1(host, arg1, operator, arg2);
}
