/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "dir.h"


void
dirprog_1(char *host, int x, int op, int y)
{
	CLIENT *clnt;
	int *result;

#ifndef	DEBUG
	clnt = clnt_create (host, DIRPROG, DIRVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	if(op == '+')
		result= suma_1(x, y, clnt);
	else if(op == '-')
		result= resta_1(x, y, clnt);
	else if(op == '*')
		result= multiplicacion_1(x, y, clnt);
	else if(op == '/')
		result= division_1(x, y, clnt);
	else
		printf("Operador no valido\n");

	
	if (result == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
		printf("El resultado es: %d\n",*result);
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int arg1, arg2;
	char operador;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	printf("Valor 1: ");
	scanf("%i",&arg1);

	printf("Operador: ");
	scanf(" %c",&operador);

	printf("Valor 2: ");
	scanf("%i",&arg2);

	host = argv[1];
	dirprog_1 (host, x, operador, y);
	exit (0);
}
