/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DIR_H_RPCGEN
#define _DIR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef char *clave;

typedef char *valor;

enum estado {
	OK = 0,
	Sustitucion = 1,
	NoEncontrado = 2,
};
typedef enum estado estado;

struct asociacion {
	clave c;
	valor v;
};
typedef struct asociacion asociacion;

struct lista {
	asociacion a;
	struct lista *sig;
};
typedef struct lista lista;

struct diccionarios {
	int id;
	lista *l;
	struct diccionarios *sig;
};
typedef struct diccionarios diccionarios;

struct resultado_obtener {
	estado e;
	union {
		valor v1;
	} resultado_obtener_u;
};
typedef struct resultado_obtener resultado_obtener;

struct resultado_enumerar {
	estado e;
	union {
		diccionarios *c;
	} resultado_enumerar_u;
};
typedef struct resultado_enumerar resultado_enumerar;

struct ponerasociacion_1_argument {
	int arg1;
	clave arg2;
	valor arg3;
};
typedef struct ponerasociacion_1_argument ponerasociacion_1_argument;

struct obtenerasociacion_1_argument {
	int arg1;
	clave arg2;
};
typedef struct obtenerasociacion_1_argument obtenerasociacion_1_argument;

struct borrarasociacion_1_argument {
	int arg1;
	clave arg2;
};
typedef struct borrarasociacion_1_argument borrarasociacion_1_argument;

#define DIRPROG 0x20000155
#define DIRVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define PonerAsociacion 1
extern  estado * ponerasociacion_1(int , clave , valor , CLIENT *);
extern  estado * ponerasociacion_1_svc(int , clave , valor , struct svc_req *);
#define ObtenerAsociacion 2
extern  resultado_obtener * obtenerasociacion_1(int , clave , CLIENT *);
extern  resultado_obtener * obtenerasociacion_1_svc(int , clave , struct svc_req *);
#define BorrarAsociacion 3
extern  estado * borrarasociacion_1(int , clave , CLIENT *);
extern  estado * borrarasociacion_1_svc(int , clave , struct svc_req *);
#define Enumerar 4
extern  resultado_enumerar * enumerar_1(int , CLIENT *);
extern  resultado_enumerar * enumerar_1_svc(int , struct svc_req *);
extern int dirprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PonerAsociacion 1
extern  estado * ponerasociacion_1();
extern  estado * ponerasociacion_1_svc();
#define ObtenerAsociacion 2
extern  resultado_obtener * obtenerasociacion_1();
extern  resultado_obtener * obtenerasociacion_1_svc();
#define BorrarAsociacion 3
extern  estado * borrarasociacion_1();
extern  estado * borrarasociacion_1_svc();
#define Enumerar 4
extern  resultado_enumerar * enumerar_1();
extern  resultado_enumerar * enumerar_1_svc();
extern int dirprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_clave (XDR *, clave*);
extern  bool_t xdr_valor (XDR *, valor*);
extern  bool_t xdr_estado (XDR *, estado*);
extern  bool_t xdr_asociacion (XDR *, asociacion*);
extern  bool_t xdr_lista (XDR *, lista*);
extern  bool_t xdr_diccionarios (XDR *, diccionarios*);
extern  bool_t xdr_resultado_obtener (XDR *, resultado_obtener*);
extern  bool_t xdr_resultado_enumerar (XDR *, resultado_enumerar*);
extern  bool_t xdr_ponerasociacion_1_argument (XDR *, ponerasociacion_1_argument*);
extern  bool_t xdr_obtenerasociacion_1_argument (XDR *, obtenerasociacion_1_argument*);
extern  bool_t xdr_borrarasociacion_1_argument (XDR *, borrarasociacion_1_argument*);

#else /* K&R C */
extern bool_t xdr_clave ();
extern bool_t xdr_valor ();
extern bool_t xdr_estado ();
extern bool_t xdr_asociacion ();
extern bool_t xdr_lista ();
extern bool_t xdr_diccionarios ();
extern bool_t xdr_resultado_obtener ();
extern bool_t xdr_resultado_enumerar ();
extern bool_t xdr_ponerasociacion_1_argument ();
extern bool_t xdr_obtenerasociacion_1_argument ();
extern bool_t xdr_borrarasociacion_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DIR_H_RPCGEN */
