/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "dir.h"

void PrintInserccion(const estado *e){
	switch(*e){
		case 0:
			printf("Correcto\n");
			break;
		case 1:
			printf("Insercción con reemplazo\n");
			break;
		case 2:
			printf("Error\n");
			break;
	}
}

void PrintBorrado(const estado *e){
	switch(*e){
		case 0:
			printf("Elemento correctamente eliminado\n");
			break;
		case 2:
			printf("No es posible eliminar ese elemento\n");
			break;
	}
}

void PrintObtener(const resultado_obtener *res){
	if((*res).e == Correcto)
		printf("El valor es: %s\n",(*res).resultado_obtener_u.v1);
	else
		printf("No se encuentra ningun resultado para los parametros indicados\n");
}

void PrintEnumerar(const resultado_enumerar *res){
	if((*res).e == Correcto){
		printf("------Lista------\n");
		diccionarios *d_aux = (*res).resultado_enumerar_u.c;

		while(d_aux->l != NULL){
			printf("%s: %s \n", d_aux->l->a.c, d_aux->l->a.v);
			d_aux->l = d_aux->l->sig;
		}
	}
	else
		printf("No se encuentra ningun resultado para los parametros indicados\n");
}

void
dirprog_1(char *host)
{
	CLIENT *clnt;
	estado  *result_1;
	int ponerasociacion_1_arg1;
	clave ponerasociacion_1_arg2;
	valor  ponerasociacion_1_arg3;
	resultado_obtener  *result_2;
	int obtenerasociacion_1_arg1;
	clave obtenerasociacion_1_arg2;
	estado  *result_3;
	int borrarasociacion_1_arg1;
	clave borrarasociacion_1_arg2;
	resultado_enumerar  *result_4;
	int enumerar_1_arg1;

#ifndef	DEBUG
	clnt = clnt_create (host, DIRPROG, DIRVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = ponerasociacion_1(ponerasociacion_1_arg1, ponerasociacion_1_arg2, ponerasociacion_1_arg3, clnt);
	if (result_1 == (estado *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = obtenerasociacion_1(obtenerasociacion_1_arg1, obtenerasociacion_1_arg2, clnt);
	if (result_2 == (resultado_obtener *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = borrarasociacion_1(borrarasociacion_1_arg1, borrarasociacion_1_arg2, clnt);
	if (result_3 == (estado *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = enumerar_1(enumerar_1_arg1, clnt);
	if (result_4 == (resultado_enumerar *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

void start(char *host)
{
	CLIENT *clnt;
	clnt = clnt_create (host, DIRPROG, DIRVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}

	int option;
	int id;
	char clave[10];
	char valor[10];
	estado  *estado;
	resultado_obtener  *consulta;
	resultado_enumerar  *listar;

	while(1){
		printf("\n¿Qué operación desea hacer?:\n");
		printf("Añadir --> 0\n");
		printf("Consultar --> 1\n");
		printf("Borrar --> 2\n");
		printf("Enumerar --> 3\n");
		scanf("%i",&option);

		if(option == 0){
			printf("\nID: ");
			scanf("%i",&id);
			printf("\nClave: ");
			scanf("%10s",clave);
			printf("\nIntroduce el valor: ");
			scanf("%10s",valor);
			estado = ponerasociacion_1(id, clave, valor, clnt);
			PrintInserccion(estado1);
		}
		else if(option == 1){
			printf("\nID: ");
			scanf("%i",&id);
			printf("\nClave: ");
			scanf("%10s",clave);
			consulta = obtenerasociacion_1(id, clave, clnt);
			PrintObtener(consulta);
		}
		else if(option == 2){
			printf("\nID:\n");
			scanf("%i",&id);
			printf("\nClave: ");
			scanf("%10s",clave);
			estado = borrarasociacion_1(id, clave, clnt);
			PrintBorrado(estado1);
		}
		else if(option == 3){
			printf("\nID: ");
			scanf("%i",&id);	
			listar = enumerar_1(id, clnt);
			PrintEnumerar(listar);
		}
	}
}

int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	
	host = argv[1];
	start (host);
	exit (0);
}
